language: node_js
sudo: false

node_js:
  - "7.0"
  - "8.0"

os:
  - osx
  - linux

branches:
  only:
  - master
  - /v?[0-9]+\.[0-9]+\.[0-9]+(.*)?/
  - /^greenkeeper/.*$/

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - ./scripts/install.sh

script:
  - npm test --silent

after_success:
  - bash <(curl -s https://codecov.io/bash)
