language: node_js
sudo: false

node_js:
  - "10.0"
  - "12.0"

os:
  - osx
  - linux

branches:
  only:
  - master
  - /v?[0-9]+\.[0-9]+\.[0-9]+(.*)?/
  - /^greenkeeper/.*$/

services:
  - xvfb

install:
  - ./scripts/install.sh

script:
  - npm test --silent

after_success:
  - bash <(curl -s https://codecov.io/bash)
